# Fake News Detection

In [1]:
# Importing necessary libraries

import os
import pandas as pd
import numpy as np
import sklearn
import nltk
import warnings
warnings.filterwarnings("ignore")

### Importing the datasets

In [2]:
df = os.chdir("D:\\Naveen\\Interview Assignments\\TomTom")

In [3]:
train = pd.read_csv("train.csv")
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
test = pd.read_csv("test.csv")
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [5]:
#check shape

print(train.shape, test.shape)

(20800, 5) (5200, 4)


In [6]:
#Checking for missing values

print(train.info())
print("-------------------")
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB
None
-------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      5200 non-null   int64 
 1   title   5078 non-null   object
 2   author  4697 non-null   object
 3   text    5193 non-null   object
dtypes: int64(1), object(3)
memory usage: 162.6+ KB
None


There are a lot of missing values. But they are all unique headlines and names of authors so we can fill all of them with empty values as they won't help in prediction. 

### Data Pre-processing

In [7]:
test=test.fillna(' ')
train=train.fillna(' ')
test['total']=test['title']+' '+test['author']+test['text']
train['total']=train['title']+' '+train['author']+train['text']

In [8]:
print(train.info())
print("-------------------")
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20800 non-null  object
 2   author  20800 non-null  object
 3   text    20800 non-null  object
 4   label   20800 non-null  int64 
 5   total   20800 non-null  object
dtypes: int64(2), object(4)
memory usage: 975.1+ KB
None
-------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      5200 non-null   int64 
 1   title   5200 non-null   object
 2   author  5200 non-null   object
 3   text    5200 non-null   object
 4   total   5200 non-null   object
dtypes: int64(1), object(4)
memory usage: 203.2+ KB
None


There are no missing values now.

In [9]:
train.head(20)

id                                              title  \
0    0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1    1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2    2                  Why the Truth Might Get You Fired   
3    3  15 Civilians Killed In Single US Airstrike Hav...   
4    4  Iranian woman jailed for fictional unpublished...   
5    5  Jackie Mason: Hollywood Would Love Trump if He...   
6    6  Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7    7  Benoît Hamon Wins French Socialist Party’s Pre...   
8    8  Excerpts From a Draft Script for Donald Trump’...   
9    9  A Back-Channel Plan for Ukraine and Russia, Co...   
10  10  Obama’s Organizing for Action Partners with So...   
11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   
12  12  Russian Researchers Discover Secret Nazi Milit...   
13  13  US Officials See No Link Between Trump and Russia   
14  14  Re: Yes, There Are Paid Government Trolls On S...   
15  15  In Major League Soccer, Argentines Find a Home...   
16  16  Wells Fargo Chief Abruptly Steps Down - The Ne...   
17  17  Anonymous Donor Pays $2.5 Million To Release E...   
18  18                          FBI Closes In On Hillary!   
19  19  Chuck Todd: ’BuzzFeed Did Donald Trump a Polit...   

                              author  \
0                      Darrell Lucus   
1                    Daniel J. Flynn   
2                 Consortiumnews.com   
3                    Jessica Purkiss   
4                     Howard Portnoy   
5                    Daniel Nussbaum   
6                                      
7                    Alissa J. Rubin   
8                                      
9       Megan Twohey and Scott Shane   
10                       Aaron Klein   
11                   Chris Tomlinson   
12                     Amando Flavio   
13                        Jason Ditz   
14                      AnotherAnnie   
15                     Jack Williams   
16  Michael Corkery and Stacy Cowley   
17                          Starkman   
18                           The Doc   
19                         Jeff Poor   

                                                 text  label  \
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1   Ever get the feeling your life circles the rou...      0   
2   Why the Truth Might Get You Fired October 29, ...      1   
3   Videos 15 Civilians Killed In Single US Airstr...      1   
4   Print \nAn Iranian woman has been sentenced to...      1   
5   In these trying times, Jackie Mason is the Voi...      0   
6   Ever wonder how Britain’s most iconic pop pian...      1   
7   PARIS  —   France chose an idealistic, traditi...      0   
8   Donald J. Trump is scheduled to make a highly ...      0   
9   A week before Michael T. Flynn resigned as nat...      0   
10  Organizing for Action, the activist group that...      0   
11  The BBC produced spoof on the “Real Housewives...      0   
12  The mystery surrounding The Third Reich and Na...      1   
13  Clinton Campaign Demands FBI Affirm Trump's Ru...      1   
14  Yes, There Are Paid Government Trolls On Socia...      1   
15  Guillermo Barros Schelotto was not the first A...      0   
16  The scandal engulfing Wells Fargo toppled its ...      0   
17  A Caddo Nation tribal leader has just been fre...      1   
18  FBI Closes In On Hillary! Posted on Home » Hea...      1   
19  Wednesday after   Donald Trump’s press confere...      0   

                                                total  
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2   Why the Truth Might Get You Fired Consortiumne...  
3   15 Civilians Killed In Single US Airstrike Hav...  
4   Iranian woman jailed for fictional unpublished...  
5   Jackie Mason: Hollywood Would Love Trump if He...  
6   Life: Life Of Luxury: Elton John’s 6 Favorite ...  
7   Benoît Hamon Wins French Socialist Party’s Pre...  
8   Excerpts From a Draft Script

In [10]:
test.head(20)

id                                              title  \
0   20800  Specter of Trump Loosens Tongues, if Not Purse...   
1   20801  Russian warships ready to strike terrorists ne...   
2   20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3   20803  Tim Tebow Will Attempt Another Comeback, This ...   
4   20804                    Keiser Report: Meme Wars (E995)   
5   20805  Trump is USA's antique hero. Clinton will be n...   
6   20806  Pelosi Calls for FBI Investigation to Find Out...   
7   20807            Weekly Featured Profile – Randy Shannon   
8   20808  Urban Population Booms Will Make Climate Chang...   
9   20809                                                      
10  20810  184 U.S. generals and admirals endorse Trump f...   
11  20811               “Working Class Hero” by John Brennon   
12  20812  The Rise of Mandatory Vaccinations Means the E...   
13  20813                Communists Terrorize Small Business   
14  20814  Computer Programmer Comes Forward, Admits To B...   
15  20815  Thieves Take a Chunk of Change, All 221 Pounds...   
16  20816  New England Patriots’ Owner, Still Sore at N.F...   
17  20817  College Republicans, YAF Sue Berkeley over Ann...   
18  20818  Trump Melts Down And Accuses The US Postal Ser...   
19  20819  Visiting Madagascar? Leave Red Swimsuits (and ...   

                        author  \
0             David Streitfeld   
1                                
2                Common Dreams   
3                Daniel Victor   
4      Truth Broadcast Network   
5                                
6                      Pam Key   
7                Trevor Loudon   
8                                
9          cognitive dissident   
10                   Dr. Eowyn   
11                Doug Diamond   
12               Shaun Bradley   
13                Steve Watson   
14              Usa News Flash   
15                Melissa Eddy   
16  Ken Belson and Ben Shpigel   
17                Tom Ciccotta   
18                Jason Easley   
19             Bryant Rousseau   

                                                 text  \
0   PALO ALTO, Calif.  —   After years of scorning...   
1   Russian warships ready to strike terrorists ne...   
2   Videos #NoDAPL: Native American Leaders Vow to...   
3   If at first you don’t succeed, try a different...   
4   42 mins ago 1 Views 0 Comments 0 Likes 'For th...   
5   Trump is USA's antique hero. Clinton will be n...   
6   Sunday on NBC’s “Meet the Press,” House Minori...   
7   You are here: Home / *Articles of the Bound* /...   
8   Urban Population Booms Will Make Climate Chang...   
9                          don't we have the receipt?   
10  Have you seen that pro-Hillary TV ad of disgra...   
11  Source: CNBC, article by Robert Ferris Arctic ...   
12  Written by Shaun Bradley   Mandatory vaccinati...   
13  Store Communists Terrorize Small Business The ...   
14  \nVIA Conservative Tribune \nIn 2000, computer...   
15  BERLIN  —   You could never palm it, flip it o...   
16  FOXBOROUGH, Mass.  —   The N. F. L. likes port...   
17  The Berkeley College Republicans and the Young...   
18  Trump warned his supporters that the US Postal...   
19  If you visit a certain beach in northeastern M...   

                                                total  
0   Specter of Trump Loosens Tongues, if Not Purse...  
1   Russian warships ready to strike terrorists ne...  
2   #NoDAPL: Native American Leaders Vow to Stay A...  
3   Tim Tebow Will Attempt Another Comeback, This ...  
4   Keiser Report: Meme Wars (E995) Truth Broadcas...  
5   Trump is USA's antique hero. Clinton will be n...  
6   Pelosi Calls for FBI Investigation to Find Out...  
7   Weekly Featured Profile – Randy Shannon Trevor...  
8   Urban Population Booms Will Make Climate Chang...  
9       cognitive dissidentdon't we have the receipt?  
10  184 U.S. generals and admirals endorse Trump f...  
11  “Working Class Hero” by John Brennon Doug Diam...  
12  The Rise of Manda

### TF-IDF

This is used to determine how important a word is to the document. Here we use "smooth_idf = False" because the terms that occur in all the records in the training set should not be entirely ignored. 

Reference: 

1. https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

### CountVectorizer

This is used to encode words into integers. This converts the text records into token counts

Reference: 

1. https://www.educative.io/edpresso/countvectorizer-in-python
2. https://www.geeksforgeeks.org/using-countvectorizer-to-extracting-features-from-text/

In [11]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

transformer = TfidfTransformer(smooth_idf=False)
count_vectorizer = CountVectorizer(ngram_range=(1, 2))
counts = count_vectorizer.fit_transform(train['total'].values)
tfidf = transformer.fit_transform(counts)

In [13]:
tfidf

<20800x3611325 sparse matrix of type '<class 'numpy.float64'>'
	with 20406542 stored elements in Compressed Sparse Row format>

In [12]:
target = train['label'].values
test_counts = count_vectorizer.transform(test['total'].values)
test_tfidf = transformer.fit_transform(test_counts)

In [14]:
test_tfidf

<5200x3611325 sparse matrix of type '<class 'numpy.float64'>'
	with 4551728 stored elements in Compressed Sparse Row format>

In [10]:
#splitting into training and test set 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tfidf, target, random_state=0)

### Fitting into a model

#### Logistic Regression 

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2398  166]
 [ 120 2516]]
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      2564
           1       0.94      0.95      0.95      2636

    accuracy                           0.94      5200
   macro avg       0.95      0.94      0.94      5200
weighted avg       0.95      0.94      0.94      5200



In [12]:
#cross validation - 5 fold

from sklearn.model_selection import cross_val_score
print(cross_val_score(logreg, X_train, y_train, cv=5))

[0.93814103 0.94551282 0.94839744 0.94134615 0.94647436]


#### Decision Tree Classifier

In [13]:
from sklearn.tree import DecisionTreeClassifier

dec_tree = DecisionTreeClassifier()
dec_tree.fit(X_train, y_train)

y_pred = dec_tree.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2460  104]
 [  89 2547]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.96      2564
           1       0.96      0.97      0.96      2636

    accuracy                           0.96      5200
   macro avg       0.96      0.96      0.96      5200
weighted avg       0.96      0.96      0.96      5200



In [14]:
#cross validation - 5 fold

print(cross_val_score(dec_tree, X_train, y_train, cv=5))

[0.96057692 0.9625     0.96153846 0.96346154 0.96570513]


#### Random Forest Classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 200, min_samples_leaf = 3, max_features = 0.5, n_jobs = -1)
rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2490   74]
 [  63 2573]]
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      2564
           1       0.97      0.98      0.97      2636

    accuracy                           0.97      5200
   macro avg       0.97      0.97      0.97      5200
weighted avg       0.97      0.97      0.97      5200



In [16]:
#cross validation - 5 fold

print(cross_val_score(rfc, X_train, y_train, cv=5))

[0.97403846 0.96826923 0.97307692 0.97628205 0.975     ]


#### Naive Bayes

In [17]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(X_train, y_train)

y_pred = mnb.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2561    3]
 [1126 1510]]
              precision    recall  f1-score   support

           0       0.69      1.00      0.82      2564
           1       1.00      0.57      0.73      2636

    accuracy                           0.78      5200
   macro avg       0.85      0.79      0.77      5200
weighted avg       0.85      0.78      0.77      5200



In [18]:
#cross validation - 5 fold

print(cross_val_score(mnb, X_train, y_train, cv=5))

[0.77532051 0.75833333 0.77532051 0.77211538 0.77307692]


#### KNN Classifier

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1780  784]
 [ 354 2282]]
              precision    recall  f1-score   support

           0       0.83      0.69      0.76      2564
           1       0.74      0.87      0.80      2636

    accuracy                           0.78      5200
   macro avg       0.79      0.78      0.78      5200
weighted avg       0.79      0.78      0.78      5200



In [20]:
#cross validation - 5 fold

print(cross_val_score(knn, X_train, y_train, cv=5))

[0.76442308 0.78012821 0.79935897 0.7849359  0.78365385]


### Checking accuracy scores of test set

In [21]:
#Logistic Regression
acc_logreg = logreg.score(X_test, y_test)*100
print(acc_logreg)

94.5


In [22]:
#Decision Tree Classifier
acc_dec_tree = dec_tree.score(X_test, y_test)*100
print(acc_dec_tree)

96.28846153846153


In [23]:
#Random Forest Classifier
acc_rfc = rfc.score(X_test, y_test)*100
print(acc_rfc)

97.36538461538461


In [24]:
#Naive Bayes
acc_mnb = mnb.score(X_test, y_test)*100
print(acc_mnb)

78.28846153846155


In [25]:
#KNN Classifier
acc_knn = knn.score(X_test, y_test)*100
print(acc_knn)

78.11538461538461


### Sorting according to test data accuracy

In [26]:
models = pd.DataFrame({
'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'KNN', 'Naive Bayes'],
'Score': [acc_logreg, acc_dec_tree, acc_rfc, acc_knn, acc_mnb]})
models.sort_values(by='Score', ascending=False)

Model      Score
2        Random Forest  97.365385
1        Decision Tree  96.288462
0  Logistic Regression  94.500000
4          Naive Bayes  78.288462
3                  KNN  78.115385

### Predicted output

In [27]:
test_id = test["id"]
submission = pd.DataFrame({"id": test_id, "label": rfc.predict(X_test)})
submission.to_csv('D:\\Naveen\\Interview Assignments\\TomTom\\submission.csv', index=False)